import pandas as pd
import subprocess
import os
import sys

# IMPLEMENTED BY SILVIA

def get_checker_result(checker_exe, txt_file):
    
    if os.path.exists(txt_file):
        try:
            # Run checker executable

            result = subprocess.run([checker_exe, txt_file], capture_output=True, text=True, timeout=10)
            output = result.stdout.lower() + result.stderr.lower()
            
            # Check for error keywords from the checker
            if "error" in output or "failed" in output:
                return "CHECKER_FAIL"
            return "CHECKER_PASS" # Schedule is valid (dependencies, resources respected)
        except subprocess.TimeoutExpired:
            return "TIMEOUT" # If the checker hangs for too long
        except Exception as e:
            return f"ERROR: {str(e)}"


def main():
    
    if len(sys.argv) < 8:
        print("Usage: python3 run_checker.py <csv_file> <checker_exe> <debug> <featS> <featP> <data_type> <alg_name>")
        sys.exit(1)

    # Parse command-line arguments
    csv_file = sys.argv[1]
    checker_exe = sys.argv[2]
    debug = sys.argv[3].lower() == 'true'
    featS = sys.argv[4].lower() == 'true'
    featP = sys.argv[5].lower() == 'true'
    alg_name = sys.argv[7]

    if not os.path.exists(csv_file):
        print(f"Error: CSV file {csv_file} not found.")
        sys.exit(1)
    
    # Load the CSV generated by C++
    df = pd.read_csv(csv_file)
    
    # List to store checker results
    checker_results = []

    for index, row in df.iterrows():

        dfg_name = row['DFG_Name']

        # Construct the text file path
        output_txt_file = f"Results/{alg_name}_{dfg_name}_S{featS}_P{featP}.txt"
        
        res = get_checker_result(checker_exe, output_txt_file)
        checker_results.append(res)
        
        if debug:   
            print(f"Checking {dfg_name}: {res}")

    # Add the checker status column to DataFrame
    df['Checker_Status'] = checker_results

    # Save the final report to a new CSV file
    final_csv_file = csv_file.replace(".csv", "_checker_report.csv")
    df.to_csv(final_csv_file, index=False)

    if debug:
        print(f"\nFinal Report generated: {final_csv_file}")


if __name__ == "__main__":
    main()